manifest:
  version: 0.7
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: juanmihdz
      url-base: https://github.com/juanmihdz
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: corneV3-ZMK
      remote: juanmihdz
      revision: main
      path: boards/shields/corne
  self:
    path: config